name: 🐧 Linux Builds
on:
  workflow_call:

jobs:
  linux:
    runs-on: ubuntu-20.04
    name: Linux Build ${{ matrix.arch }}
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, x86_32, arm64, rv64]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build ${{ matrix.arch }}
        uses: ./.github/actions/build
        with:
          arch: ${{ matrix.arch }}
          platform: linux

      - name: Upload ${{ matrix.arch }}
        uses: ./.github/actions/upload
    
