name: 🍎 macOS Builds
on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: Godot Box2D
          path: godot-box2d
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: godot-box2d
      - name: Delete draft release(s)
        uses: hugo19941994/delete-draft-releases@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: paulhatch/semantic-version@v5.3.0
        id: version
        with:
          bump_each_commit: true
          tag_prefix: "v"
          debug: true
      #- name: Release
      #  uses: softprops/action-gh-release@v1
      #  with:
      #    name: ${{ steps.version.outputs.version }}
      #    files: godot-box2d/*
      #    draft: true
      #    prerelease: true
